name: Aria2-Fast Build x64

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: build arai2c.exe
      env:
        BRANCHE: master
      run: |
        curl -L -o Dockerfile.mingw "https://raw.githubusercontent.com/aria2/aria2/$BRANCHE/Dockerfile.mingw"
        bash patch_dockerfile.sh
        sudo docker build --build-arg HOST=x86_64-w64-mingw32 --build-arg ARIA2_VERSION=$BRANCHE --build-arg ARIA2_REF=refs/heads/master -t aria2-mingw - < Dockerfile.mingw
        id=$(sudo docker create aria2-mingw)
        sudo docker cp $id:/aria2/src/aria2c.exe ./aria2c-fast_x64.exe
    - name: Upload to release
      uses: JasonEtco/upload-to-release@master
      with:
        args: aria2c-fast_x64.exe application/vnd.microsoft.portable-executable
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
